// <auto-generated />
using System;
using LabScaner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabScaner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LabScanerDbContext))]
    [Migration("20261004192026_AddDirectories")]
    partial class AddDirectories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabScaner.Core.Directory.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdmissionYear")
                        .HasColumnType("integer")
                        .HasColumnName("admission_year");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name_key");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_groups_name_key");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("LabScaner.Core.Directory.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("GroupId", "LastName", "FirstName")
                        .HasDatabaseName("ix_students_group_id_last_name_first_name");

                    b.ToTable("students");
                });

            modelBuilder.Entity("LabScaner.Core.Directory.StudentEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_student_emails");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_student_emails_email");

                    b.HasIndex("StudentId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_student_emails_student_id_email");

                    b.ToTable("student_emails");
                });

            modelBuilder.Entity("LabScaner.Core.Directory.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("academic_year");

                    b.Property<DateOnly>("CreditWeekStart")
                        .HasColumnType("date")
                        .HasColumnName("credit_week_start");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("season");

                    b.Property<DateOnly>("SessionStart")
                        .HasColumnType("date")
                        .HasColumnName("session_start");

                    b.HasKey("Id")
                        .HasName("pk_terms");

                    b.HasIndex("AcademicYear", "Season")
                        .IsUnique()
                        .HasDatabaseName("ix_terms_academic_year_season");

                    b.ToTable("terms");
                });

            modelBuilder.Entity("LabScaner.Core.Directory.Student", b =>
                {
                    b.HasOne("LabScaner.Core.Directory.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_students_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("LabScaner.Core.Directory.StudentEmail", b =>
                {
                    b.HasOne("LabScaner.Core.Directory.Student", null)
                        .WithMany("Emails")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_emails_students_student_id");
                });

            modelBuilder.Entity("LabScaner.Core.Directory.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("LabScaner.Core.Directory.Student", b =>
                {
                    b.Navigation("Emails");
                });
#pragma warning restore 612, 618
        }
    }
}
